
title: Kunal Rajpal
email: rajpalk@myumanitoba.ca
description: >- # this means to ignore newlines until "baseurl:"
  Simple portfolio website made using Jekyll and GitHub pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "KunalRajpal.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kunalrajpal_
github_username:  KunalRajpal

# Build settings
theme: minima
plugins:
  - jekyll-feed

